runtime: nodejs18

env: standard
instance_class: F1

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  NODE_ENV: "production"
  # Do not store actual API keys here. Use Secret Manager instead.
  # These are placeholders for documentation only
  GOOGLE_MAPS_API_KEY: "YOUR_GOOGLE_MAPS_API_KEY"
  GOOGLE_PLACES_API_KEY: "YOUR_GOOGLE_PLACES_API_KEY"
  NEXT_PUBLIC_GOOGLE_CUSTOM_SEARCH_API_KEY: "YOUR_GOOGLE_CUSTOM_SEARCH_API_KEY"
  NEXT_PUBLIC_GOOGLE_SEARCH_ENGINE_ID: "YOUR_GOOGLE_SEARCH_ENGINE_ID"
  NEXT_PUBLIC_FIREBASE_API_KEY: "YOUR_FIREBASE_API_KEY"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "YOUR_FIREBASE_AUTH_DOMAIN"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: "YOUR_FIREBASE_PROJECT_ID"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "YOUR_FIREBASE_STORAGE_BUCKET"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "YOUR_FIREBASE_MESSAGING_SENDER_ID"
  NEXT_PUBLIC_FIREBASE_APP_ID: "YOUR_FIREBASE_APP_ID"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: "YOUR_FIREBASE_MEASUREMENT_ID"
  NEXT_PUBLIC_GROQ_API_KEY: "YOUR_GROQ_API_KEY"
